model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    embed_dim: 4
    monitor: val/rec_loss
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 10000
        kl_weight: 1.0e-6
        disc_weight: 0.5
        perceptual_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 4
    train:
      target: ldm.data.cifar.CIFAR10Train
      params:
        size: 32
    validation:
      target: ldm.data.cifar.CIFAR10Validation
      params:
        size: 32

lightning:
  trainer:
    benchmark: True
    max_epochs: 100
    gpus: 1
    precision: 32