model:
  base_learning_rate: 1.0e-4
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0001
    linear_end: 0.02
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 8
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [2000]
        cycle_lengths: [10000000000]
        f_start: [1.e-6]
        f_max: [1.0]
        f_min: [1.0]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 8
        in_channels: 4
        out_channels: 4
        model_channels: 64
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_heads: 4
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "logs/2025-07-25T14-09-05_autoencoder_cifar10/checkpoints/last.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 32
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 4
    wrap: False
    train:
      target: ldm.data.cifar.CIFAR10Train
      params:
        size: 32
    validation:
      target: ldm.data.cifar.CIFAR10Validation
      params:
        size: 32

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 150
    precision: 32
